services:
  _defaults:
    autowire: true
    autoconfigure: true
    bind:
      $awsRegion: '%env(string:AWS_REGION)%'
      $awsEndpoint: '%env(string:AWS_ENDPOINT)%'
      $awsKey: '%env(string:AWS_ROOT_USER)%'
      $awsSecret: '%env(string:AWS_ROOT_PASSWORD)%'
      $awsBucket: '%env(string:AWS_BUCKET)%'
      
  _instanceof:
    App\Controller\AbstractController:
      tags: ['controller.service_arguments']

  App\:
    resource: '../src/*'
    exclude:
      - '../src/Kernel.php'
      - '../src/{Api,Entity,Exception}'
