services:
  _defaults:
    autowire: true
    autoconfigure: true
      
  _instanceof:
    App\Controller\AbstractController:
      tags: ['controller.service_arguments']

  App\:
    resource: '../src/*'
    exclude:
      - '../src/Kernel.php'
      - '../src/{Entity,Exception}'
