version: "3.7"
services:
  php:
    build:
      target: php_dev
      dockerfile: ./.docker/php/Dockerfile
      context: ./
    volumes:
      - ./:/application
    depends_on:
      - db
      - db-test
      - minio
      - mailhog

  nginx:
    build:
      dockerfile: ./.docker/nginx/Dockerfile
      context: ./
    ports:
      - ${NGINX_PORT}:80
    depends_on:
      - php

  db:
    image: postgres:15.0-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432
    env_file:
      - .env
      - .env.local

  db-test:
    image: postgres:15.0-alpine
    env_file:
      - .env

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    ports:
      - 9001:9001
    volumes:
      - aws-data:/data
    env_file:
      - .env
      - .env.local

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - 8025:8025

volumes:
  aws-data:
  db-data:
