version: "3.7"
services:
  php:
    build:
      target: php_dev
      dockerfile: ./.docker/php/Dockerfile
      context: ./
    volumes:
      - ./:/application
    depends_on:
      - db
      - db-test
      - minio

  nginx:
    build:
      dockerfile: ./.docker/nginx/Dockerfile
      context: ./
    ports:
      - ${NGINX_PORT}:80
    depends_on:
      - php

  db:
    image: mysql:8.0
    volumes:
      - db-data:/var/lib/mysql
    env_file:
      - .env
      - .env.local

  db-test:
    image: mysql:8.0
    env_file:
      - .env

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    ports:
      - 9001:9001
    volumes:
      - aws-data:/data
    env_file:
      - .env
      - .env.local

volumes:
  aws-data:
  db-data:
